### ISSUE TITLE
MidiQoL Conflict

### ISSUE THREAD

**Issue by wardmanm** [TheComamba/UnKenny#88]
Foundry V12.327
Unkenny V1.0.3
MidiQoL V11.4.37

Issue: If MidiQoL is enabled Unkenny no longer finds actor alias in chat and does not respond. 

Example: 
![image](https://github.com/TheComamba/UnKenny/assets/5400857/5973e908-7e6b-4d69-aed3-1b66db0fda0d)
![image](https://github.com/TheComamba/UnKenny/assets/5400857/509afeaa-a861-436a-b4f8-51b4f7937f65)

Midi QoL Settings attached.
[fvtt-midi-qol-settings.json](https://github.com/user-attachments/files/15974754/fvtt-midi-qol-settings.json)

**Comment by TheComamba** [comment]
Oopsie. As a first hunch this may be related to #90. We will investigate.

**Comment by TheComamba** [comment]
I recant my hunch and will properly start investigating now. :D

**Comment by TheComamba** [comment]
I figured out what was going on.
@wardmanm The conflict will be fixed with the next release, which I hope to publish in a few minutes.
@KingphilAusti The people from MidiQol had the same bad idea we had: Overwriting the ChatMessage class. Only they do it twice, once on the init hook, and once on the setup. My quick fix is that we call our function in the setup hook instead of the init hook. I think this only works because "Unk" is after "Midi" in the alphabet. Their ChatMessage overwrite does not check if there is any other class currently set, but simply overwrites the DnD5e class. I'll drop them an issue asking them to adopt a design similar to ours.

**Comment by TheComamba** [comment]
@wardmanm Done. Thanks for bringing this to our attention. :)

**Comment by wardmanm** [comment]
Awesome, great work!
