### ISSUE TITLE
Add Mistral 7B OpenChat 3.5 to local hosted models 

### ISSUE THREAD

**Issue by KingphilAusti** [TheComamba/UnKenny#95]
Model shows good performance for open source models. 
- https://huggingface.co/openchat/openchat_3.5
- https://huggingface.co/mistralai

Mistral 22B could also be interesting but currently I suppose that would not work license wise.

**Comment by TheComamba** [comment]
Openchat [does not seem to have any models for transformer.js](https://huggingface.co/models?pipeline_tag=text-generation&library=transformers.js&sort=modified&search=openchat).

There is one transformer.js model called [tiny-random-mistral](https://huggingface.co/models?pipeline_tag=text-generation&library=transformers.js&sort=modified&search=mistral), which does not sound very promising. Especially since I am not sure if this is even a chat completion model, or "just" text generation.
