### ISSUE TITLE
Whisper to GM unKenny NPC setting

### ISSUE THREAD

**Issue by sengokudaikon** [TheComamba/UnKenny#99]
Hi, first of all, thanks for the awesome module.
I wanted to request a feature, or any clarification if it's already possible to do so. A toggle that would tell the unKennied actors to /w gm <the response from llm> instead of publicly posting it to chat. I thought that it was inconvenient that whenever I want to prepare a reply for my players, I'd have to manually hide the messages, and they will see the response.
Also, unsure how that will interact with /talk.

In any case, I hope you'll at least see and consider this.

Much appreciated, best regards

**Comment by KingphilAusti** [comment]
Hey, 

thank you for your request. I tested the obvious with "please start you message with /w gm." that but did not work. We will look into it!
How do you imagine the feature? Like an additional command you add in the chat like "#gmwisper" or a setting for the NPC itself? 

Best, Phil

**Comment by sengokudaikon** [comment]
> Hey,
> 
> thank you for your request. I tested the obvious with "please start you message with /w gm." that but did not work. We will look into it! How do you imagine the feature? Like an additional command you add in the chat like "#gmwisper" or a setting for the NPC itself?
> 
> Best, Phil

Hi, Phil, thanks for the reply.
I initially thought of a configuration checkbox. When I as GM use /talk <text>, I manually input the text that was provided by the model, in a previous message. So, might be something like a "Make all messages player whispers" in the settings, which would make all model responses be directed to the player or GM that triggered the response?

hashtags perhaps could be used to automatically use /talk option, if the GM/player doesn't care about editing responses of the models. I don't have much experience with foundry modding, but from the relevant discussions in the discord, these workarounds can be tedious.

**Comment by KingphilAusti** [comment]
Ok. I will look into it. 
Yes could be a bit problematic to change the message and have it processed again by foundry and/or other modules. Should work but does not seem so right now. We will see.

**Comment by TheComamba** [comment]
Starting with "/w <player> /talk" does not evaluate the /talk macro. I haven't tried the other way round because I don't have an Elevenlabs token. I suspect that "Reading stuff out loud but only to one person" is not a use-case. So I'm fine with making the two options "Prefix with talk" and "Prefix with whisper" mutually exclusive.
Also the whisper macro is currently not evaluated if we have our module post it.
I suggest this approach:
- [ ] Replace the "prefix with talk" checkbox with a dropdown menu. That's the easy part.
- [ ] Add the whisper prefix at a point in the code where it is evaluated by Foundry. That's the tedious part.
